"""DIMER inference and bounded fine-tuning package for the pinned YOLOX-X checkpoint.

The modules beside this one whose names come from upstream YOLOX (``network_blocks``, ``darknet``,
``yolo_pafpn``, ``losses``, ``yolo_head``, ``yolox``, ``coco_classes``, ``ops``) are vendored upstream
code, not part of this package's public surface; see ``docs/UPSTREAM.md``. Everything this package
offers is re-exported here from ``pipeline``.
"""

from .pipeline import (
    ARTIFACT_FILE,
    ARTIFACT_FORMAT,
    COCO_IOU_THRESHOLDS,
    DEFAULT_BATCH_SIZE,
    DEFAULT_EPOCHS,
    DEFAULT_LEARNING_RATE,
    DEFAULT_SEED,
    DEFAULT_WEIGHTS_DIR,
    DETECTION_THRESHOLD,
    EVAL_DETECTION_THRESHOLD,
    EVAL_NMS_THRESHOLD,
    INPUT_SCHEMA,
    INPUT_SIZE,
    LABELS,
    MANIFEST_NAME,
    MAX_CLASSES,
    MAX_DETECTIONS,
    MAX_EPOCHS,
    MAX_IMAGE_SIDE,
    MAX_LABELS_PER_IMAGE,
    MAX_TRAIN_IMAGES,
    MIN_IMAGE_SIDE,
    MODEL_DEPTH,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    MODEL_WIDTH,
    NMS_THRESHOLD,
    PAD_VALUE,
    RELEASE_ASSET_URL,
    TRAIN_SCHEMA,
    UPSTREAM_CODE_REVISION,
    YoloxXDetectionPipeline,
    average_precision,
    box_iou,
    evaluation_report,
    preprocess,
    split_records,
    stage_missing_files,
    validate_dataset,
    validate_image,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "ARTIFACT_FILE",
    "ARTIFACT_FORMAT",
    "COCO_IOU_THRESHOLDS",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_EPOCHS",
    "DEFAULT_LEARNING_RATE",
    "DEFAULT_SEED",
    "DEFAULT_WEIGHTS_DIR",
    "DETECTION_THRESHOLD",
    "EVAL_DETECTION_THRESHOLD",
    "EVAL_NMS_THRESHOLD",
    "INPUT_SCHEMA",
    "INPUT_SIZE",
    "LABELS",
    "MANIFEST_NAME",
    "MAX_CLASSES",
    "MAX_DETECTIONS",
    "MAX_EPOCHS",
    "MAX_IMAGE_SIDE",
    "MAX_LABELS_PER_IMAGE",
    "MAX_TRAIN_IMAGES",
    "MIN_IMAGE_SIDE",
    "MODEL_DEPTH",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "MODEL_WIDTH",
    "NMS_THRESHOLD",
    "PAD_VALUE",
    "RELEASE_ASSET_URL",
    "TRAIN_SCHEMA",
    "UPSTREAM_CODE_REVISION",
    "YoloxXDetectionPipeline",
    "average_precision",
    "box_iou",
    "evaluation_report",
    "preprocess",
    "split_records",
    "stage_missing_files",
    "validate_dataset",
    "validate_image",
    "validate_inputs",
    "verify_snapshot",
]
